import type { Intl } from './types';

export const _FIELDS_TYPES = [
  'text',
  'select',
  'checkbox',
  'number',
  'color',
  'email',
  'date',
  'time',
  'url',
  'tel',
  'datetime-local',
  'image',
  'file',
  'week',
  'conditional',
] as const;

export const INTL: Intl = {
  fr: {
    title: 'Générateur de formulaire',
    description:
      'Créez un formulaire personnalisé avec des champs dynamiques.',
    addField: 'Ajouter un champ',

    field: 'Champ',
    types: {
      text: 'Texte',
      select: 'Choix',
      checkbox: 'Case à cocher',
      number: 'Chiffre',
      color: 'Couleur',
      email: 'Email',
      date: 'Date',
      time: 'Heure',
      url: 'URL',
      tel: 'Téléphone',
      'datetime-local': 'Date et heure',
      image: 'Image',
      file: 'Fichier',
      week: 'Semaine',
      conditional: 'Conditionnel',
    },
    delete: 'Supprimer',
    question: 'Intitulé de la question',
    option: { placeholder: 'Option', invite: 'Votre choix' },
    answer: { placeholder: 'Réponse' },
  },
  en: {
    title: 'Form Generator',
    description: 'Create a custom form with dynamic fields.',
    addField: 'Add Field',
    field: 'Field',
    types: {
      text: 'Text',
      select: 'Choice',
      checkbox: 'Checkbox',
      number: 'Number',
      color: 'Color',
      email: 'Email',
      date: 'Date',
      time: 'Time',
      url: 'URL',
      tel: 'Phone',
      'datetime-local': 'Date and Time',
      image: 'Image',
      file: 'File',
      week: 'Week',
      conditional: 'Conditional',
    },
    delete: 'Delete',
    question: 'Question Title',
    option: { placeholder: 'Option', invite: 'Your choice' },
    answer: { placeholder: 'Answer' },
  },
  es: {
    title: 'Generador de formularios',
    description: 'Crea un formulario personalizado con campos dinámicos.',
    addField: 'Agregar campo',
    field: 'Campo',
    types: {
      text: 'Texto',
      select: 'Elección',
      checkbox: 'Casilla de verificación',
      number: 'Número',
      color: 'Color',
      email: 'Correo electrónico',
      date: 'Fecha',
      time: 'Hora',
      url: 'URL',
      tel: 'Teléfono',
      'datetime-local': 'Fecha y hora',
      image: 'Imagen',
      file: 'Archivo',
      week: 'Semana',
      conditional: 'Condicional',
    },
    delete: 'Eliminar',
    question: 'Título de la pregunta',
    option: { placeholder: 'Opción', invite: 'Tu elección' },
    answer: { placeholder: 'Respuesta' },
  },
};
