name: Playwright e2e Tests

on:
  push:
    paths:
      - 'src/routes/**'
      - 'src/ui/**'
      - 'playwright.config.ts'
      - 'package.json'
      - '.github/workflows/playwright.e2e.yml'

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
        type: string
        default: 'main' # Default branch to test if not specified

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: 'mcr.microsoft.com/playwright:v1.50.0-noble'
      options: '--user root' # run as root to avoid permission issues
    env:
      CI: true # signal CI mode to Playwright (often not strictly needed, but good practice)
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key:
            docker-${{ runner.os }}-${{ hashFiles('docker-compose.yaml') }}

      - name: 'Install node'
        uses: actions/setup-node@v4@
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          version: 10
          run_install: true

      - name: lint
        run: pnpm run lint

      - name: Run Playwright tests
        run: pnpm run test:e2e
        env:
          # Fix Firefox crash in GitHub Actions
          # Details: https://github.com/microsoft/playwright/issues/6500#issuecomment-838515115
          HOME: /root

      - name: Upload Playwright report on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
